#!/bin/bash
## ---------------------------------------------------------------------
## Copyright (C) 2019 - 2021 by the lifex authors.
##
## This file is part of lifex.
##
## lifex is free software; you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## lifex is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with lifex.  If not, see <http://www.gnu.org/licenses/>.
## ---------------------------------------------------------------------

# Author: Pasquale Claudio Africa <pasqualeclaudio.africa@polimi.it>.

##
## This script has been readapted from the corresponding file
## available at the deal.II development repository
## (https://github.com/dealii/dealii),
## released under compatible license terms
## (please consult the doc/licenses directory for more information).
##

#
# This script indents all source files of lifex according to our usual
# code formatting standards. It is used to ensure that our code base looks
# uniform, as uniformity helps make code easier to read.
#
# While we're already touching every file, this script also makes
# sure we set permissions correctly and checks for correct unix-style line
# endings.
#
# The script needs to be executed as
#   ./scripts/format/indent_all
# from the top-level directory of the source tree, or via
#   make indent_all
# from a build directory.
#
# The script can be invoked with lifex_CLANG_FORMAT to change
# the default version of clang-format. For example:
#   lifex_CLANG_FORMAT=clang-format-10.0.0 ./scripts/format/indent_all
# or,
#   make lifex_CLANG_FORMAT="clang-format-10.0.0" indent_all
#
# Note: If the script is invoked with REPORT_ONLY=true set,
#   REPORT_ONLY=true ./scripts/format/indent_all
# or,
#   make REPORT_ONLY=true indent_all
# then indentation errors will only be reported without any actual file
# changes.
#

if [ ! -f extra/indent/indent_common ]; then
  echo "*** This script must be run from the top-level directory."
  exit 1
fi

source extra/indent/indent_common

# Run sanity checks.
checks

# Process all source and header files.
process ". source models extra build" ".*\.(cpp|hpp)" format_file

# Fix permissions and convert to unix line ending if necessary.
process ". source models extra build" ".*\.(cpp|hpp)" fix_permissions
process ". source models extra build" ".*\.(cpp|hpp)" dos_to_unix
