#!/bin/bash
## ---------------------------------------------------------------------
## Copyright (C) 2024 by the DUBeat authors.
##
## This file is part of DUBeat.
##
## DUBeat is free software; you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## DUBeat is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with DUBeat.  If not, see <http://www.gnu.org/licenses/>.
## ---------------------------------------------------------------------

# Author: Matteo Calafà <matteo.calafa@mail.polimi.it>.

##
## This script has been readapted from the corresponding file
## available at the lifex development repository
## (https://gitlab.com/lifex/lifex),
## released under compatible license terms.
##



if [ ! -f extra/indent/indent_common ]; then
  echo "*** This script must be run from the top-level directory."
  exit 1
fi

source extra/indent_common

# Run sanity checks.
checks

# Process all source and header files.
process_changed ". source models extra build" ".*\.(cpp|hpp)" format_file

# Fix permissions and convert to unix line ending if necessary.
process_changed ". source models extra build" ".*\.(cpp|hpp)" fix_permissions
process_changed ". source models extra build" ".*\.(cpp|hpp)" dos_to_unix
